export enum API {
  tenants = '/api/tenants',
  vehicles = '/api/vehicles',
  reservations = '/api/reservations',
  tickets = '/api/tickets',
  incidents = '/api/incidents',
  users = '/api/users',
  diets = '/api/diets',
  dietCollections = '/api/diet-collections',
  dietPhotos = '/api/diet-photos',
  login = '/api/login',
  register = '/api/register/create_fake',
  reservationTemplates = '/api/reservation-templates',
  lastPositions = '/api/positions',
}
